_docs/objects.md

Also deleted sentence fragment.

Added autocomplete description

---

_docs/docker.md

A few minor typo fixes

---

_docs/development.md

This is a short write up on how Jonathan gets his development environment
set up. It may be useful for others who want to contribute.

Add Contributing section

---

_docs/logic.md

This question was left incomplete. The wording was taken from: https://docassemble.org/docs/modifiers.html#scan%20for%20variables

Complete unfinished sentence

---

_docs/functions.md

(moved from docassemble.base.util to docassemble.base.functions)

Fixed reference to update language functions

---

_docs/officeaddin.html

There is an empty page that came up when I was searching.
I added a link to the page, as I'm not sure if this will eventually be expanded.
If not, adding a hard redirect may be a better choice.

Add link to empty page

---

_docs/recipes.md

I'd prefer if it used a generic object block for the different types of individuals, but I wasn't able to get that working, quickly.

Add recipe for a master list of Individuals

---

docassemble_base/docassemble/base/util.py

Changes to pronoun_subjective(), pronoun(), pronoun_possessive(). Pronoun_possessive() uses their() which is already defined in functions.py.

Add 'other' to the genders in Individual

---

docassemble_base/docassemble/base/functions.py

expanded on the phone number functions

added phone number formatted function

---

docassemble_base/docassemble/base/util.py

I've tested this as a function in a local install, but not on main branch. Also need to add google-i18n-address as a dependency for this to work.

New address block method

---

_docs/recipes.md

A recipe for converting 2nd person language to either 2nd or 3rd person language.

Proposed Recipe

---

docassemble_demo/docassemble/demo/data/questions/examples/preview.yml

"if action_argument('likes_mushrooms'):" returned True when either True or False was selected. With added "== 'True'" it work like intended.

IF condition fix

---

docassemble_base/docassemble/base/filter.py

Used width and height attributes, as per the google article at
https://web.dev/optimize-cls/.
Wasn't able to test with video files, so I left them alone. I did
notice the youtube video layout shift seems to be already handled
with css!
Tried to ensure current defaults in the cases where width and
height aren't available. Not quite sure of the file wrangling.

Reduce layout shift for images and documents with fallback if err

---

.gitignore
docassemble_base/setup.py
docassemble_webapp/setup.py

See https://docs.python.org/3/library/pathlib.html

Removing pathlib since it's a core library in python 3

---

docassemble_base/docassemble/base/pdftk.py

It's difficult to understand what might be happening with pdftk when it silently fails. After this PR, if pdftk errors, it's stderr output will be shown to the user.
TBH it's not super clean, but I'd rather have that info than trying to reproduce the error on the system itself, which usually happens with files in `tmp` that don't exist by the time I see the issue.
Screenshot of what it makes the error screen look like below:
(Side note, this particular error in pdftk is fixed in 3.3.2, but it doesn't seem to be released to the latest Ubuntu yet for some reason, not sure why).

Add more information to pdftk error screens

---

docassemble_webapp/docassemble/webapp/server.py

There are two parts to this PR:
* replaces `werkzeug.utils.secure_filename` for git branches, which aren't filenames, and have [a lot of other valid forms](https://git-scm.com/docs/git-check-ref-format) (most relevant to our use case: names with slashes in them, like `releases/v4`).
* while this will still replace certain bash metacharacters like \` , `$`, `"`, and `'`, I'm entirely sure it's safe, as I'm not familiar with [all of the mechanisms that bash uses to evaluate things and when they occur]( https://stackoverflow.com/a/56688189/11416267). I left it in, in case, and it can't hurt security by being there, and shouldn't matter too much with the next part of the PR...
* avoid using `shell=True` in `subprocess.check_output`.
* When trying to make sure I had successfully bash escaped …

Allow installing branches with '/' in the name

---

deploy.md

Just adding our company to the list of consultants

Add "Legal Tech Helper" to the list of consultants

---

docassemble_base/docassemble/base/pandoc.py

Logs them if it we can't convert a DOCX to PDF for some reason.
We had a bit where convert DOCXs to PDFs wouldn't work on our production server (stack trace below), when using libreoffice. We can (and probably will) switch to unoconv, but I figured it would help to have more information about why a particular run of either failed, similar in spirit to #586. 
<summary>stack trace<details>
<pre>
Traceback (most recent call last):
File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File …

Save the output of libreoffice and unoconv runs

---

docassemble_base/docassemble/base/util.py

Fixing the Pandas error that I found in creating a table. Based on the documentation, this looks to be right, but I wasn't able to rebuild it and test locally since I'm on a Mac.

Update util.py for Pandas 2.0.3

---

docassemble_base/docassemble/base/parse.py

There is no indication on existing error screens what line of the input YAML file where the error is happening. This, combined with the fact that some error messages have incorrect line numbers, is very confusing for Docassemble users of all skills.
This PR adds the starting line number of the block for all errors. It additionally corrects line numbers for [`yaml.errors.MarkedYAMLError`s](https://github.com/yaml/pyyaml/blob/155ec463f6a854ac14ccd5e2dda8017ce42a508a/lib/yaml/error.py#L48), which are most errors emitted when parsing YAML.

Added correct line numbers in errors

---

docassemble_base/docassemble/base/parse.py

Currently, when a code block fails at runtime, the only piece of information in the stack trace is `<code block>`, with no indication where the code block was located.
This PR adds the `id_debug` function to Questions, and uses it to get info about the file and line number of the code block. It puts this info in compiled `validation code` and `code` blocks, so if they fail at runtime, the error contains a relevant file and line number.
An example of what the stack trace looks like now:

Show detailed info about compiled code blocks

---

deploy.md

No longer offering Docassemble consulting

Remove Documoose
