jhpyle/docassemble

_docs/installation.md
When manually installing on Ubuntu 16.04, I had to run autoreconf in order to compile configure.
=> Add autoreconf

docassemble_base/docassemble/base/file_docx.py
This merge also puts the html_names dictionary back into the add_to_rt method which should solve the phantom closing tag problem that was seen in integration testing.
=> Add Multiformat Lists, Paragraph Lists, and Blockquotes

_docs/objects.md
This adds some documentation to clarify the process of initializing
a local variable from a remote file, e.g. a remote .pdf which the
author wants to use as a fillable template.
=> Add documentation for initializing from remote file

_docs/template.md
The example uses `content file` but documentation had `source file`.
=> Fix to Match Example

docassemble_base/docassemble/base/core.py
I'm assuming 1773 should match 1774 and call _da_dict_add and not _da_list_add
=> correct url_only responses for DADict.add_action()

docassemble_webapp/docassemble/webapp/update.py
The present version checks values between two database tables, but does not check against the output of pip freeze.  The below variables are already defined
packages = supposed to be installed per database table package (id)
package_by_name = supposed to be installed per database table package(name)
here_already = already installed (output of pip freeze)
installs = supposed to be installed on this server per database table install (this = loop iter of servers)
=> Ensure packages expected to be installed are indeed installed

docassemble_base/docassemble/base/file_docx.py, docassemble_base/docassemble/base/parse.py
This commit uses docxcompose (a new dependency) to fix up images, shapes, etc from subdocs that are included using include_docx_template. The images and shapes should now show up properly without issue and styles should be properly transferred across.
I've done testing for a bunch of different cases, but there is the worry that this could break things that currently work. That said, it should enable much more modular templating, allowing things like a standard signature which is included in all of the generated documents.
=> Fix subdoc images, shapes, styles, footnotes, etc

_docs/docker.md
List of containerroles omitted `cron` in the configuration options. This adds it back in.
=> add cron to configuration options list

_docs/functions.md
added a negative to show that get_config returns none when not defined, not when defined.
=> fixed get_config returns none when not defined

_docs/development.md, _docs/packages.md
* Add install private repos information in package management as well
* Change format of private repo url to a more user friendly notation. (Both URL formats work IRL) 
* More beginner friendly instruction on constructing private repo URL
* Slightly more specific instructions on generating a personal token
=> Add more information on Github private repos.

docassemble_base/docassemble/base/data/sources/fr-words.yml
A french user of ours pointed out that the translation for the 'Clear' button for signatures should be 'Effacez' and not 'Nettoyer'.
=> Change to french translation for 'Clear'

docassemble_webapp/docassemble/webapp/server.py
Since result is not defined in this context, the call to logmessage instead raises a NameError instead of proceeeding to the next iteration.
=> fixed logmessage call that raises a NameError 

docassemble_base/docassemble/base/filter.py
In a repo I'm working in, we have an import `from docassemble.base.pandoc import (..., ..., ...)`. This caused an error because: 
- `pandoc.py` includes `import docassemble.base.filter`
- `filter.py` includes `from docassemble.base.pandoc import MyPandoc`
This causes a circular import. I found [this solution](https://stackoverflow.com/questions/22187279/python-circular-importing) and implemented it in my local copy of docassemble, and it fixed the issue.
=> Fixing circular import

_docs/fields.md
Also explain why we use `y` rather than `x` in our lambda function.
=> Add example lambda expression for `validate` field modifier.

_docs/documents.md
Rewrite of the section about line breaks in Jinja2 to highlight the new default behavior and clearly explain when and how line breaks in user input will be turned into paragraphs and other consequences of those options.
=> Clarify method to preserve user line breaks

docassemble_base/docassemble/base/standardformatter.py
Both question-level and choice-level help sections can use markdown formatting. With this change, help sections on the field level  can use markdown formatting as well.
=> Enable markdown formatting in field-level help

_docs/functions.md
Removed a duplicated paragraph about `question_name` (kept the paragraph with slightly more explanation), and added the clarifier that you can't set variables for the current session.
=> Updated `set_session_variables` documentation

docassemble_base/docassemble/base/core.py
Right now on HEAD, if you call `DAFile.get_pdf_fields()`on a PDF with no fields, you'll get a `'NoneType' object is not iterable` error (in full below). This is just happening because docassemble tries to immediately iterate over returned object, even if it's none.
This change just checks for and forwards the `None` object if it's present.
Can add any testes if necessary, I couldn't find where to add any. But a similar patch is working on our [Weaver interview](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/pull/251/files#diff-48c88c3fcd4d754a1b6bdd0e739d8ef79da95bb640718aef2afd712e989db71aR1070).  Currently trying to ensure this works on a docker image, but still in progress. 
----------------------------
```
During handling of the above exception, another exception …
```
=> Don't throw error if there are no fields in PDF

_docs/logic.md, _docs/objects.md
Fixed a few copy paste issues in the documentation that I came across, and also added very sparse parameter names to functions where appropriate. The existing documentation for each function was good, but the added parameter names, in my opinion, clarify what exactly the parameters can take.
=> Documentation Copy-paste errors and some function param info

docassemble_base/docassemble/base/config.py, docassemble_webapp/docassemble/webapp/microsoft.py, docassemble_webapp/setup.py
I have added very basic support for Azure Key Vault secret reference strings embedded within the config file.
**Please consider reviewing the proposed changes and integrating them as you see fit.**
_Note: this update does not extend the managed identity to Azure Storage authentication, users will still need to provide the initial Azure Storage keys to access the configuration file. The managed identity is just currently enabled for Key Vault access - however the full managed identity authentication scenario using no stored keys end-to-end (including Azure Storage) could be achieved with additional small updates._
> #### Pre-requisites:
> 1. Whatever Azure service is running the Docassemble application (Virtual Machine, App Service, AKS) will need to have a system-assigned managed identity …
=> Feature adding key vault reference support within config file

docassemble_webapp/docassemble/webapp/server.py
Adds gherkin scripts as default editable, without having to change `editable extensions`.
Given that [the documentation](https://docassemble.org/docs/development.html#bdd) talks about using gherkin / `.feature` scripts, it makes sense for that extension to be editable as text in the playground. The only other type of file that uses `.feature` extension is [Visual Studio](https://extension.nirsoft.net/feature), which shouldn't really show up in DA projects, and even then it's still XML, so you won't accidentally flood the editor with binary and possibly corrupt things.
=> Default editable gherkin scripts

docassemble_base/docassemble/base/core.py
This was sparked by an issue we had when we tried adding a subclass of `DAList`: the resulting sum was a DAList and didn't have the methods that we had added to our subclasses.
This PR uses `self.__class__` to construct new objects from the class, which means when people subclass these classes, these methods that construct new object are the correct subclass.
Has been tested on our wizard code without [this patch](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/blob/master/docassemble/assemblylinewizard/interview_generator.py#L636-L646), but might warrant a bit more testing.
=> Use `self.__class__` instead of `ClassName` when making new objects.

docassemble_webapp/docassemble/webapp/server.py
Currently, if you pass a Github URL to the /updatepackage page, for example, `https://github.com/SuffolkLITLab/docassemble-ALDocument/`, the server will run:
```
pip install --no-cache-dir --quiet --prefix=/usr/share/docassemble/local3.8 --src=/tmp/tmp6w2i9cb2 --upgrade --log-file=/tmp/tmpmuy02yb5 git+https://github.com/SuffolkLITLab/docassemble-ALDocument/.git@main#egg=docassemble.ALDocument
```
adding `.git` directly to the end. The easy fix to this is to strip off the ending slash at input time.
I had some options here: either strip the `/` off the URLs directly after receiving them from the user, or right before installing them to the package database (in `install_git_package`). I went with the former, as the URLs are first checked with `user_can_edit_package`, which wouldn't …
=> Strip ending '/'s off github URLs

docassemble_base/docassemble/base/data/questions/examples/date-limit.yml, tests/features/TestExamples.feature
In the [docs on dates](https://docassemble.org/docs/fields.html#date), the default date description and the min/max description have the same example.
These should be separate. I'm making this PR first, and will add to the docs in the gh-pages branch once this goes in.
Also saw that there are tests for the examples now, I tried to add a test for the new example, but not sure if the "should see the phrase" command matches partial strings. We can't hardcode the exact string to see because it's setting a max of `today()`. Let me know if there's anything I should change there.
=> Added a new example on max in dates, to be referenced in the docs

docassemble_base/docassemble/base/core.py
Related to #363: fixes the same issue, but in DAStaticFile, which I missed at the time.
=> Don't throw error if no fields in a StaticFile

docassemble_base/docassemble/base/util.py
Making it equivalent to using DAFile with `overlay_pdf`. A simple workaround is to just use `static_file_obj.path()`, but it's a simple change.
=> Allows a DAStaticFile to be passed to overlay_pdf

docassemble_base/docassemble/base/parse.py, docassemble_base/docassemble/base/util.py
This patch makes it possible to create your own jinja filters, which may be preferrable to using regular functions. Example module code:
```python
def placeholder_filter(value, placeholder, stringify=str):
rt = RichText()
if value is None:
rt.add("[")
rt.add(placeholder, highlight="yellow")
rt.add("]")
else:
rt.add(value)
return rt
register_jinja_filter("or", placeholder_filter)
``` 
This can later be used as any other jinja filter in your docx files, eg  `{{customer_name | or(”Please enter the name of the customer”) }}`
=> new function: register_jinja_filter

_docs/modifiers.md
The modifier `sets` is explained both in section 21 and section 27. The first explaination seems like the most simple to me, so maybe the other could be removed?
=> sets is documented twice

docassemble_base/docassemble/base/functions.py
[Lambda expressions](https://docs.python.org/3/reference/expressions.html#lambda) need to have either
a parameter list (and thus a space right after the 'lambda') or be immediately followed by a colon. The regex used
by the `value()` function to search for lambdas would improperly throw an error if the name of the
variable being sought contained the word 'lambda' anywhere, even if it wasn't a python lambda.
This change corrects the regex in `value` to only throw an error when the word lambda is followed by
a space or a colon.
=> Let 'lambda' appear in the names of variables

docassemble_webapp/docassemble/webapp/users/forms.py
No longer fails in the `PhoneLoginVerifyForm`, since to the `remote_addr` was being passed
and not the flask request.
This commit seems to be related to https://github.com/jhpyle/docassemble/commit/2d8057a032aab449817d1d2e8b128b2326307d8b, where a lot of similar changes were made, but not here.
=> Caught a missing refactor for get_requester_ip

.gitignore, docassemble_base/docassemble/base/parse.py
Adds class `DASkipUndefined` which handles Jinja2 undefined, callable, attributes, etc. and returns an empty string. `__eq__` and `__ne__` both return False instead of empty string.
This makes it possible to use `skip undefined: True` with a DOCX file, such as in a custom `error action` that lets someone download work that is still in progress.
Test file demonstrating a template with both defined and undefined values:
```
---
mandatory: True
code: |
users = "ABCDEF"
---
mandatory: True
question: |
Hello, There
attachment: 
docx template file: sample_word_template.docx
skip undefined: True
```
[sample_word_template.docx](https://github.com/jhpyle/docassemble/files/7445044/sample_word_template.docx)
=> Add "skip undefined" option to DOCX template files

.gitignore, docassemble_base/docassemble/base/parse.py
1. Handle all possible parameters for the built-in "dunder" Python methods
2. Specifically handle Docassemble's initialization of the DASkipUndefined object in certain circumstances where DA tries to pass parameters to the undefined class's `__init__` method that we didn't handle before.
=> Fix bugs in DOCX `skip undefined`

docassemble_base/docassemble/base/parse.py
Another round of revisions to the DASkipUndefined which catches some more unexpected issues w/ complex templates, mostly to do with some dunder methods that are expected to return a specific type and handling for loops.
Attaching a test DOCX which shows the cases that this should handle now. I think this is quite comprehensive, other than handling `__radd__`, `__rmod__` and `__rdiv__`, which appears to be an upstream bug. Oddly enough the other right-handed methods are fine.
[test_da_skipundefined.docx](https://github.com/jhpyle/docassemble/files/7597136/test_da_skipundefined.docx)
Raised an issue for this on https://github.com/elapouya/python-docx-template/issues/399
=> Patch docx skip undefined

_docs/objects.md
The examples were checking a page token to see if there were
more results for a particular search, but they never reused
that page token for the next query, leading to an infinite loop.
=> Corrected an error in DAGoogleAPI examples

docassemble_webapp/docassemble/webapp/server.py
This is in addition to https://github.com/jhpyle/docassemble/pull/462 to support backwards compatibility for filenames that have multiple consecutive spaces.
=> Multiple spaces in filename regression.

docassemble_base/docassemble/base/error.py, docassemble_base/docassemble/base/util.py, docassemble_webapp/docassemble/webapp/listlog.py, docassemble_webapp/docassemble/webapp/users/forms.py
Had a report that `NameError: name 'select' is not defined` happened webapp/user/forms.py today on production. When fixing that (which was a simple missing import), I started fixing a few other related 'undeclared variable' errors that I picked up from pylint. I haven't run into those issues on production, but they do seem to be real bugs. All of the bugs I haven't personally seen or had reported I stuck in the 2nd commit, if you wish to examine them closer or test yourself.
=> Fix undeclared imports and variables

docassemble_webapp/docassemble/webapp/server.py
No matter the address handed in, if the user has github integration then try using ssh to pull. If they don't, use a non-ssh cloning address.
When pulling from GitHub, a private repo needs a `git@` url to use SSH instead of the non-ssh url. If github integration isn't set up, though, trying to use the SSH url will cause an error. Currently, when the `playground_pull` API is used, the requester has to know which url to send.
It occurred to me that instead of requiring the requester to know whether a person's repository was private, or whether a user has github integration, docassemble's API may be able to use the knowledge it has about the user's github integration to give it the best shot it could have.
I had a hard time telling if `do_playground_pull()` is also used to install …
=> Handle API github pull url complexities internally

_docs/documents.md
1.2.68 - 2021-05-13
Changed
Upgraded various dependencies, including docxtpl, the new version of which allows images to be inserted into headers and footers of DOCX files.
=> Inserting images into docx footer possible from 1.2.68

docassemble_webapp/docassemble/webapp/server.py
I can do it with the others as well, but this was the function I could test at the moment.
Returning a Promise makes it easier for developers using that function to `await` the results synchronously or chain with `.then()` etc. [They can also continue to use the callback.]
=> Return $.ajax Promise for `get_interview_variables()`

docassemble_base/docassemble/base/filter.py
Not sure I managed to trigger `image_as_rtf()` properly, but the
other worked without a hitch and it seems a pretty benign change.
=> Ensure image files are closed after opening

_docs/fields.md
Used to point to the `no-label-field` instead of the correct demo.
=> Corrected label-above-field demo

.dockerignore, Docker/config/docassemble.ini.dist, docassemble_webapp/setup.py
I recently ran into [a bug where `sys.executable` wasn't `python`](https://docassemble.slack.com/archives/C7791ATUJ/p1645831035613809?thread_ts=1645713090.060679&cid=C7791ATUJ), as it should be. I checked out uWSGI, and they just [fixed this bug in the most recent version](https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.20.html?highlight=sys.executable#changes). There are a few other updates as well, but they mostly look like bug fixes.
I tested this on a new docassemble docker image, and the `sys.executable` is `python`, as expected. Using this demo interview:
```
imports:
- sys
---
mandatory: True
question: |
sys.executable:
subquestion: |
${ sys.executable }
---
```
gives the following on docassemble without this patch:
and gives the follow on docassemble with this patch: …
=> Correct executable

docassemble_base/docassemble/base/functions.py
Two changes:
* `showifdef`, `value`, and `defined` all used the `components_of` function. However, the `components_of` function doesn't handle complex nesting, just returning wrong values for some question (for example, using one variable as an index into another variable). This PR fixes that bug, and also adds support for binary operations in expressions, which is useful for `showifdef` or `value`.
* to implement the above, I combined the code for `showifdef`, `value`, and `defined`, which all have an identical function body, just with different return behaviors (`value` specifically just calls `force_ask` each time the other functions return). This change should make things a bit simpler, It also should save a small bit of compute for lots of showifs in a row that are all defined, since …
=> Combined logic for showifdef, value, and defined

docassemble_base/docassemble/base/parse.py, docassemble_base/docassemble/base/standardformatter.py, docassemble_webapp/docassemble/webapp/server.py
Allows interview authors to specify optgroups for options. Helps organize options in `select` tags into a single level hierarchy. It's implemented by looking for a `group` attribute in each choice, and sorting those groups in the same order that they first appear in the choices attnibute, and then inserting an `<optgroup>` tag at the beginning of each group.
The label of the `<optgroup>` tag is the same string as the "group" attribute.
A version of this has been running in production for a few weeks now, and this particular code has been tested with:
* a single `dropdown` attribute, without the `fields` attribute
* manually specifying choices
* choices from code
If the `shuffle` attribute is enabled, each of the groups are shuffled around, and the items within each group is shuffled.
More …
=> Add optgroups

docassemble_webapp/docassemble/webapp/server.py
Caught with pylance -- it looks like `transform_json_variables()` is the correct function name
=> Fix incorrect function reference

docassemble_base/docassemble/base/filter.py, docassemble_base/docassemble/base/standardformatter.py, docassemble_webapp/docassemble/webapp/server.py, docassemble_webapp/docassemble/webapp/templates/pages/interviews.html, docassemble_webapp/docassemble/webapp/templates/pages/update_package.html
I have been doing an accessibility audit for a docassemble interview, and these are some changes needed to be made in DA core to make the interview accessible. Possibly more to come, but there were present on most every page in the nav bar.
* added the tab role to the help/question tablist in the banner
* moved source and question tabs out of the tab list, just regular divs
They aren't really tabs, as the ARIA definition of tabs are panels
where only one displays at a time. Changed some CSS classes to make sure they display the same.
* hide the tab list element if empty (no help, chat, or phone). Elements with the role "tablist" are assumed to always have children, so if there aren't any children, we should remove it
* use the semantic "hidden" attribute just to make things a little …
=> Interview WCAG

_docs/accessibility.md, _docs/config.md, _docs/functions.md, _docs/initial.md, _docs/interviews.md, _docs/objects.md, _docs/questions.md, _docs/recipes.md
Things were [updated to Bootstrap 5.0](https://github.com/jhpyle/docassemble/commit/b8eb2212f2bd7a5dbe6f66bc03253c39fd6dc699) a while back, so I updated the relevant links in the documentation to point to bootstrap 5.
=> Changed all links to bootstrap stuff to bootstrap 5.0

docassemble_base/docassemble/base/parse.py, docassemble_base/docassemble/base/util.py
Invalidate is referenced in a more inner for loop, but not in an outer for loop.
Also used an existing function when generating the name of a dictionary value
=> Add invalidate to special review field commands

_docs/fields.md
Added a brief explanation of why it is necessary to mention `val()` in a `js show if` expression, as well as explanation of the most common JavaScript syntax used in `js show if` and links to Mozilla documentation for more details.
=> Add some extra info about js show if

.gitignore, docassemble_base/docassemble/base/standardformatter.py
If there is only one field on a page (like when using a separate `field`
attribute and something like `dropdown`), we know the best label for it is the
same label that the form gets, the #daMainQuestion element. While the
information might be redundant, in my opinion it's better than a select field
with no label at all.
This same issue also happens when you give `no label` in a list of fields with just one field, but the refactoring there needed to make the desired change is much more significant, so I figured I'd start with this change.
=> Add aria-labelledby to solo-fields on pages

docassemble_base/docassemble/base/parse.py
If you set `address autocomplete` to False in an address.address field, the value saved by the server is still True.
Our reason for setting the `address autocomplete` to False is so our `address_fields()` (https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/f7d1144c1ff4a0535bfd143b5c320a38c28cb493/docassemble/AssemblyLine/al_general.py#L72) is can check if the server has the correct google maps api key; if it does, then we set it to true, if something is missing, then we set it to false, to avoid a javascript error on the page.
=> Let the `address_autocomplete` attribute be false

docassemble_base/docassemble/base/file_docx.py
Composer.restart_first_numbering seems to be expecting paragraphs only, and misjudges the numbering used in tables, such that using a named numbering style anywhere in the table leads to the insertion of a number in the first table cell if that uses a named paragraph style.
Fixes #574
=> When fixing up a subdoc, don't call restart_first_numbering for tables

docassemble_base/setup.py
It's used in `util.py:send_email`. With this addition, you can install `docassemble.base` without installing `docassemble.webapp`, and call (most) of the functions. Doesn't entirely work, but all of the dependencies are present now.
=> Add Flask_Mail as a dependency of docassemble.base

docassemble_webapp/docassemble/webapp/server.py
If we don't show any pypi information on the package screen, don't query pypi for it.
I did some testing of why opening the package screen takes a while on certain servers. From some of my tests, calling pypi can take ~1/3rd of the load time (from [py-spy](https://github.com/benfred/py-spy) samples), so this should give a small speed boost to those with pypi turned off on their servers.
`can_publish_to_pypi` is calculated for both GET and POST, and it's only dependent on configs (the POST vars assume it was on when GET returned the form), so adding it to the `if` should change semantics. Tested on a small local server, and worked as expected (the pypi status of a package was shown correctly on the packages screen when turned on).
=> Don't call for pypi status if turned off on server

docassemble_base/docassemble/base/util.py
If at least two of the keys in a `data` block match the `DAContext` names, create a `DAContext` instead of a plain `DADict`. This allows the author to create custom keys without losing the DAContext's behavior.
=> Match DAContext if at least two keys match, not exclusive

docassemble_base/docassemble/base/marisol/marisol.py, docassemble_base/docassemble/base/util.py, docassemble_base/setup.py
Was running into some performance of bates numbering on large PDFs (~700 pages, taking 2 or 3 minutes and timing out consistently). PyPdf's `mergePage()` function, used in `marisol.py`, seemed to take up much of the compute. I'm not sure why.
I changed it to use `pikepdf` instead, which has a similar `add_overlay()` function, that doesn't copy each page from the PDF individually. Since marisol hasn't been updated since 2017, it's likely safe to fork from it. If there are updates from upstream, I'd be happy to merge those personally.
Test results:
On 17 various PDFs (gathered from my local machine, so they have personal info,
happy to DM the files if wanted), with a total of 1659 pages,
* before this PR, took 226.35 seconds
* after this PR, took 13.13 seconds
* no visible difference on the …
=> Improve performance of bates numbering

docassemble_webapp/setup.py
sklearn is intentionally breaking pip builds for 5 minutes of every hour at the moment, slowly increasing until it's broken, I've run into this a few times when installing docassemble packages. See this github repo for the full details: https://github.com/scikit-learn/sklearn-pypi-package
=> sklearn is deprecated for scikit-learn

docassemble_base/docassemble/base/filter.py, docassemble_base/docassemble/base/standardformatter.py
Including in `buttons` and `choices` image attributes, not just inline. The [icon documentation](https://docassemble.org/docs/config.html#default%20icons) suggests that this should be the case every where, and this PR brings everything up to line with that expectation.
Necessary to show font-awesome icons from different styles, like "brand".
Here's a test interview to show the new functionality, and that it doesn't break existing font awesome functionality.
```yml
mandatory: True
question: |
Choose a Design Library
decoration:
pencil
subquestion: |
:fab-fa-bootstrap:
:pencil:
buttons:
- Bootstrap: bootstrap_stuff
image: fab-fa-bootstrap
- Pencil and Paper: pencil_and_paper
image: pencil
```
On 1.4.30:
With this patch:
Tested with decoration as well to make sure it works.
=> Lets you use font-awesome prefixes everywhere

docassemble_base/docassemble/base/pdftk.py
In PDFs, Radio buttons are terminal fields that can still have children ("Kids", in the PDF object), which are annotations that display the value of the radio button, checking or circling the selected button choice. 
Radio buttons from Adobe are formatted differently than other programs; the `Kids` annotations don't have the `Ft` (field type) (and aren't required to by the PDF spec). So when `read_fields` recurses down into `Kids`, if it can't find a field type and the Kid is actually marked as an annotation, we should remember the parent's field type and use it instead.
An example PDF, and the results of `pdftk.read_fields` before this change:
```python
[('Group1', 'something', 1, [162.937, 631.267, 180.937, 649.267], None, None),
('Group1', 'something', 1, [164.241, 601.938, 182.241, …
```
=> Be able to read radio buttons properly

docassemble_base/docassemble/base/pdftk.py
Currently docassemble can set the value of a radio button correctly. However,
in some PDF viewers (I tested in Ubuntu's Evince document viewer), the selected
radio button doesn't appear properly. This is because while docassemble
sets `/V` on the radio button group annotation, it doesn't set the `/AS`
(appearance stream) of the child annotation, which some viewers use to
actually which radio button is selected.
This PR makes the following changes to fix the issue:
* allows `export_values` to handle multiple values on the same field.
For radio buttons, means that if a template already has a radio button
selected, it won't override the given value in `data_strings`.
* Children of terminal fields don't have to have either FT or T, so
look until a parent does and don't stop if the kid has FT, …
=> Write radio buttons and checkboxes for more viewers

docassemble_base/docassemble/base/file_docx.py, docassemble_base/docassemble/base/filter.py, docassemble_base/docassemble/base/pandoc.py, docassemble_base/docassemble/base/pdftk.py, docassemble_base/docassemble/base/util.py
As mentioned in the [pikepdf documentation](https://pikepdf.readthedocs.io/en/latest/topics/pages.html#pdf-split-merge-and-document-assembly),
we should close the PDF files after using them. Letting them hang around can
cause issues with python and C++ references.
One issue that this patch seems to fix is a potential issue with calling
`pdf_concatenate` under load. Before this patch, with 6 individual sessions
of the [Assembly Line Weaver](https://github.com/SuffolkLITLab/docassemble-ALWeaver)
open in different browsers, I can consistently get the following error
to appear in the `uwsgi.log`:
```
terminate called after throwing an instance of 'std::runtime_error'
what():  pybind11_object_dealloc(): Tried to deallocate unregistered instance!
DAMN ! worker 1 (pid: 666329) died, killed by …
```
=> Close PDF files after using

docassemble_webapp/docassemble/webapp/server.py
Instead of calling `abort`, return the 400 errors as the other errors are returned. Doesn't show the full docassemble screen as normal, but it does prevent error logs from appearing, and matches the other ways of returning errors.
=> Return the 400 speakfile errors like other errors

docassemble_webapp/docassemble/webapp/files.py, docassemble_webapp/docassemble/webapp/server.py
Setuptools has deprecated `description-file`, and given a specific date after which it will start breaking installing certain packages (Sept 26 2023).
This patch changes docassemble's output of packages from `description-file` to the suggested replacement, `description_file`.
The full pip error:
******************************************************************************** 
Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead.
By 2023-Sep-26, you need to update your project and remove deprecated calls or your builds will no longer be supported.
See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
********************************************************************* …
=> description-file -> description_file

docassemble_webapp/docassemble/webapp/server.py
In some interviews, we have the following restart link (in the footer, but the location on the screen shouldn't matter):
```mako
${ url_of('restart') } )
```
If a user is not logged in, DA crashes. The issue is that the `restart_session` endpoint expects an email to be present.
This fixes the issue by passing `None` as the email, which happens in other places for not logged in users as well.
=> Don't always pass email as session uid

docassemble_base/setup.py, docassemble_webapp/setup.py
From the reportlab mailing list:
>    These fix a potential security vulnerability in the parsing of colours.
Previously, Iif someone had coded an application allowing user-input
expressions to be passed to our toColor constructor function, there was a
way to execute inappropriate code.  If you are doing this, please upgrade
to the newest version.
>    If, however, there are no external inputs and colours are set by you in code
(or validated to be simple and reasonable expressions), there is no vulnerability.
I don't see any uses of `toColor` in docassemble, but I'm not sure if there are internal uses of `toColor` in reportlab that docassemble still uses, or if docassemble users use `toColor` in their own applications. So, better to be safe, but I wouldn't prioritize it or call it urgent.
=> Update reportlab to 3.6.13 for security patch

docassemble_base/docassemble/base/pdftk.py
`parse.py` turns all "True" and "False"-like values into "Yes" and "No", presumably for text conversion and how push buttons work. However, this breaks radio buttons, which need exact string matching to properly set their values.
This PR turns the data_string values back into `"True"` and `"False"` if a particular field is a radio button, which we don't know before then.
Tested with an example from the slack; this interview:
```yml
question: |
Select one ?
field: is_check
buttons:
- YES: True 
- NO: False
---
mandatory: true
question: Check Done.
subquestion: |
${ is_check }
attachment:
- name: check
filename: check
pdf template file: check.pdf
fields:
- "radio-button": ${ is_check }
```
filling in this PDF:
[check.pdf](https://github.com/jhpyle/docassemble/files/11454611/check.pdf)
=> Allow "True" and "False" as radio button choices

docassemble_base/docassemble/base/file_docx.py
Ideally, `_use_jinja2=True` should act the same as the default call to `include_docx_template`, since True is the default. However, since `include_docx_template` doesn't remove the param from `kwargs`, the function will fail later when it tries to encode the value of the param.
The error looks like:
```
"/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/file_docx.py", line 168, in include_docx_template   
the_repr = '_codecs.decode(_array.array("b", "' + re.sub(r'\n', '', codecs.encode(bytearray(val, encoding='utf-8'), 'base64').decode()) + '".encode()), "base64").decode()' 
TypeError: encoding without a string argument`.
```
Easy work around (just don't pass `_use_jinja2` if you use True), but also a pretty easy fix that I've had sitting around for a while. …
=> Allow `_use_jinja2=True` in include_docx_template

_docs/functions.md
The current documentation accidentally uses a table because the `|` is not properly escaped. It also uses `{%p` when it should use `{{p`.
Added brief mention of the two optional parameters, `width` and `alt_text`.
=> Fix documentation for qr_code in DOCX templates

docassemble_webapp/docassemble/webapp/server.py
This continues on work in https://github.com/jhpyle/docassemble/commit/8d1b84777ce626170e44d83e09de523bbfca5e50#diff-4c8bf136c393acf44c18098d2b935b3a005636e57574530acffdf552432360faR5751 (1.4.0). That commit ran avoided running the results from a refresh from a background action, but only if `do_action` was set. There is also a section that get the final values from finished workers directly that hadn't been calling `safe_json` on the results, causing errors like: 
```
File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 6250, in checkin
return jsonify_with_cache(success=True, chat_status=chatstatus, num_peers=num_peers, help_available=help_available, phone=call_forwarding_message, observerControl=observer_control, commands=commands, …
```
=> JSON-ize things returned from a background action

.github/workflows/codeql.yml
(note: un-solicited contribution)
It seems that when adding [codeql](https://github.com/jhpyle/docassemble/commit/c4268e330fa504767ec87aa1aaae563aab48fca4), GitHub detected `sample.cpp` in docassemble_demo, and thought that this repo contained C++ code. This isn't correct, and since then, codeql complains loudly that the C++ workflow fails (and sends me silly emails about it).
This removes that workflow. Feel free to clarify if the C++ workflow is intentional and ignore this PR if that is the case.
=> Remove cpp from workflow

docassemble_webapp/docassemble/webapp/backend.py
Currently calling `user_access` or `privilege_access` with no args on a DAFile will result in an error. Not sure why but `.scalars()` in this context returns a list containing only the resulting id.
Using `.all()` returns the expected list of `UploadsUserAuth` or `UploadsRoleAuth` objects.
Confirmed broken functionality on the newest version of v1.4.72 on a clean install with the below interview:
```yaml
question: |
Please upload a picture
fields:
- Picture: user_picture
datatype: file
---
code: |
user_picture[0].privilege_access('user')
got_access = user_picture[0].privilege_access()
---
question: Picture
subquestion: |
${ user_picture }
got access: ${ got_access }
mandatory: True
```
=> fix DAFile user_access and privilege_access list

docassemble_webapp/docassemble/webapp/watchdog.py
I've been using some runtime-introspection tools (particularly [`stubtest`](https://mypy.readthedocs.io/en/stable/stubtest.html)) on docassemble's code base recently, and when you simply `import watchdog`, the tool will get stuck in an infinite loop because the only thing in the file is an infinite `while: True` loop.
This patch puts that behind `if __name__ == '__main__'`, so only people who are running this module as the main module will get the desired infinite loop. The only documented way of running this module is through `run-watchdog.sh`, which runs `python -m docassemble.webapp.watchdog &`, so this shouldn't break any existing functionality.
Tested running in a built docker image, the watchdog process still is running after starting the container, so looks to be all good.
=> Put watchdog loop behind `__name__ == '__main__'`

docassemble_webapp/docassemble/webapp/backend.py
I have recently seen production errors that are:
```
File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/backend.py", line 775, in fetch_user_dict
user_dict = decrypt_dictionary(d.dictionary, secret)
File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/backend.py", line 744, in decrypt_dictionary
decrypter = AES.new(bytearray(secret, encoding='utf-8'), AES.MODE_CBC, dict_string[:16])
TypeError: encoding without a string argument
```
That error occurs when something that isn't a string is passed into `bytearray` with the `encoding` argument.
I have no idea how the `UserDict` could have an entry in a text column that isn't null but also isn't a string, but it seems to have happened. This check will make sure that we don't …
=> Ensure user_dict from DB is string

docassemble_webapp/docassemble/webapp/server.py
Currently, it is hard to spot an API key on the screen when it is generated. This separates the API key visually with an alert and uses the `kbd` element as opposed to `code` which better indicates the ability to copy and paste.
I've also added a simple copy button.
Visually, I tried to emulate the API key generation appearance from GitHub which is very plain but still easy to read.
New appearance:
Comparison to GitHub:
Some UX pattern research: https://carbondesignsystem.com/community/patterns/generate-an-api-key/
=> Make it easier to see API key

docassemble_base/docassemble/base/parse.py
This lets us have a `features: bootstrap theme:` block in another package, that we can then include in the current interview. Previously, DA would try to look for a locally referenced bootstrap theme in the current package, i.e. "custom_bootstrap.css" wouldn't work, and you would have to put "docassemble.other_package:custom_bootstrap.css".
Implemented with `hasattr`, since there are a few places that `bootstrap_theme` could come from, and checking for it's existence seemed simpler than adding an extra variable that also tracked where `bootstrap_theme` was set from.
Tested locally and it works as expected.
=> Keep track of package the bootstrap theme is from

docassemble_base/docassemble/base/functions.py
This PR changes all `inspect.stack()[1][0]` to `sys._getframe(1)` which results in an average speed improvement of 5x EACH time the system searches for a variable. For my test interview, on the front end, I saw a 27x speed improvement (from 0.46s to 0.017s) using the same interview, starting a new session each run, and only changing the code in this PR.
Reasoning:
`inspect.stack()` is slow because it collects the entire stack and builds the context for each step, which is then discarded by the stack and frame selection `[1][0]`
I saw a 2x speed improvement just by disabling the context loader with `inspect.stack(0)[1][0]`
Validation:
Using a debugger I verified that the original code gets the frame of the caller this is important because it's recommended to use `inspect.currentframe()` …
=> Frame search speed optimizations

docassemble_base/docassemble/base/functions.py
If you don't keep looking for `old_user_dict`, you might first reach objects that still exist in the rewound `user_dict`, which might exist, but won't have attributes set before the back button press.
Specifically fixed a bug found when modifying https://docassemble.org/docs/background.html#background_response to be used on an object (at the bottom).
Happy to modify or do any more testing; it seems like it could be a big change, but does seem like the right behavior for `prior=True`.
```yaml
objects:
- address: Address
---
question: |
Where do you live?
fields:
- Country: address.country
code: countries_list()
- State: state
code: |
states_list(country_code=showifdef('address.country', 'US', prior=True)) or ['N/A']
js enable if: val('address.country')
check in: update_states_list
--- …
```
=> When `prior=true`, keep looking for `old_user_dict`

_docs/docker.md
Using an S3 compatible service can be confusing. Added an explicit example of how to take the URL that the service gives you, which typically includes the bucket name already, and deconstruct it for Docassemble's env.list.
=> Clarify how to use S3-compatible services

docassemble_base/docassemble/base/parse.py
`review` is considered a directive, and should be listed as one.
=> Add `review` to the list of directives on error

docassemble_webapp/docassemble/webapp/server.py
When `login link style` is "normal" with a wide screen, the login links are styled differently: one as a plain, unmarked link, and one as a button. Screen shot of vanilla docassemble below:
While the aesthetic isn't bad, the usability suffers, as it's not clear either at a glace or when hovering, that "Sign up" is a clickable link. This gets worse when modifying the bootstrap theme (see https://github.com/mplp/docassemble-mlhframework/issues/87 for this original discussion, where it's more pronounced using our modified nav bar color).
This change makes the links consistent on narrow screens and on wide screens: either both links on narrow screens (in the dropdown) or both buttons on wider screens.
Additionally fixed an issue where there would be no login URL using login link style and not …
=> Make "Sign up" & "Sign in" similar w/ login links

docassemble_webapp/docassemble/webapp/templates/base_templates/base.html
While trying to help a developer customize the logo in the top left of the register/sign-in page, we were getting the logo tripled.
After digging through `docassemble_webapp/docassemble/webapp/templates/base_templates/base.html` it appears that the `register page title` overrides `page_title` which in turn is used to customize `<meta itemprop="name"...`, `<meta name="twitter:...`, and `<meta name="og:title"...>`, but there is no escaping done to remove HTML.
It seems that while `page_title` is fine to have HTML, these specific places it is doubled-up shouldn't get nested HTML. If the included HTML in `... page title` configuration includes quotes, the HTML is broken and doesn't render properly.
This PR removes the first-level HTML and then escapes any other potentially problematic …
=> Allow customizing title to add HTML without breaking meta tags

docassemble_base/docassemble/base/parse.py
This fixes #805 (but may have other side effects -- but it seems safer to run fix_subdoc before render since render may cause dangling bookmarkEnd tags, that renumber_bookmarks() then will renumber incorrectly).
=> avoid calling fix_subdoc twice (only in include_docx_template)

_docs/packages.md
Edit: This tweak was based on the assumption that this section of the documentation was for packages one installs and works on in the Playground. That may be incorrect. Here's [some other documentation (about Playground packages) that jhpyle pointed me to](https://docassemble.org/docs/playground.html#packages). These two may or may not be related. That's unclear to me now. I'll leave my PR in case it's still relevant, but this might not be accurate. I'd be happy to edit it once I understand better.
---
Apparently `dependency_links` got removed with version 19. Instead, you put the information in `install_requires` with special formatting. This format worked for me to install a GitHub dependency during ALKiln test runs:
```
install_requires=['github-package-name @ …
```
=> Update `install_requires` dependency docs to example from pip >= 19

_docs/api.md, _docs/background.md, _docs/config.md, _docs/development.md, _docs/docker.md, _docs/documents.md, _docs/errors.md, _docs/fields.md, _docs/functions.md, _docs/groups.md, _docs/initial.md, _docs/installation.md, _docs/interviews.md, _docs/language.md, _docs/livehelp.md, _docs/markup.md, _docs/objects.md, _docs/special.md, _docs/twotothree.md
I updated all of the links to Python documentation, as well as update all of the references for interacting with Python in Docker containers from `3.10` -> `3.12`.
I also expanded the Docassemble/Python version explanation on the `twotothree` page.
=> fix: update Python venv references to align with changes in v1.7.0, `3.10` -> `3.12`

docassemble_base/docassemble/base/parse.py, docassemble_base/docassemble/base/standardformatter.py
This PR adds support for the HTML5 `datalist` as an input type for fields.
I propose adding `datalist` as an alternative input type to `combobox`. They fill very similar niches, but `datalist` is a standard HTML5 supported tag which requires no additional JavaScript, has better accessibility, and has wide browser support.
In docassemble, I specifically ensure support for `hint` and `number`/`integer` datatypes.
You can try a basic example of a `datalist` on the [W3Schools Tryit Editor](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist) and you can see a Bootstrap example [in their docs](https://getbootstrap.com/docs/5.2/forms/form-control/#datalists).
Some webpages that support the addition of `datalist`:
["Datalist over ARIA …
=> feat: add input type 'datalist' to fields

docassemble_base/docassemble/base/data/questions/examples/fields-choices-datalist.yml
I copied and modified the `fields-choices-combobox.yml` to use `datalist`.
=> Add example for input type `datalist`

_data/example.yml, _docs/fields.md
I wrote a new section for `datalist` (right above combobox) and added `datalist` to some other relevant references/places in the `fields.html` page.
=> Add documentation for input type `datalist`

Docker/config/config.yml.dist, Docker/initialize.sh, docassemble_base/docassemble/base/config.py, docassemble_base/docassemble/base/pandoc.py
Gotenberg added basic auth recently, which is highly encourged when running it on a publically visible URL. https://github.com/gotenberg/gotenberg/issues/684
This change adds `gotenberg: username` and `gotenberg: password` to the config to allow docassembl to call gotenberg servers secured like this. It splits the config to still respect the original `gotenberg url: ...` config or to handle the config being under an attribute, like such.
```yaml
gotenberg:
url: ...
username: ...
password: ...
```
as well as adding the corresponding env vars `GOTENBERGUSERNAME` and `GOTENBERGPASSWORD`.
Tested that the original config works, as well as spinning up a new server with the gotenberg URL.
Writing up documentation for the new config values now as well.
=> Added Basic Auth for Gotenberg servers
